images._error: write message to body in error case
Currently we return a generic varnish error page when we hit ANY
error, which is confusing for users. It also leads to a `hit-front`
status which is confusing for SREs debugging and general traffic
stats.

Bug: T417577
Change-Id: If8fe07402fbbcb1020bb34a701ab4425f4bda84a